
export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const CURRENT_USER_PETS = "CURRENT_USER_PETS";
export const OTHER_USER_PETS = "OTHER_USER_PETS"

//CONSTANTE PARA SACAR LAS PUBLICACIONES DEL USUARIO ACTUAL
export const USER_STATE_CHANGES = "USER_STATE_CHANGES";
export const USER_POST_STATE_CHANGE = "USER_POST_STATE_CHANGE";

//CONSTANTES FUTURAS PARA SACAR TODAS LAS PUBLICACIONES//
export const USERS_DATA_STATE_CHANGE = "USERS_DATA_STATE_CHANGE"
export const USERS_POSTS_STATE_CHANGE = "USERS_POSTS_STATE_CHANGE"
//----------------------//
export const CURRENT_USERS = "CURRENT_USERS"
//--------------------//
export const CLEAR_DATA = "CLEAR_DATA"
//--------------------//
export const CURRENT_SHELTER_PET_REQUESTS ="CURRENT_SHELTER_PET_REQUESTS"
//--------------------//
export const USERS_PETS_DATA ="USERS_PETS_DATA"

export const USER_FAV_STATE_CHANGE ="USER_FAV_STATE_CHANGE"
export const CLEAR_FAVS = "CLEAR_FAVS"

//--------------------------//
export const CHATS_SET = "CHATS_SET"